server:
  port: 8022
spring:
  application:
    name: excel-manager
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/excel_manager
    username: root
    password: 12345678

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9081/realms/dev
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  realm: dev
  domain: http://localhost:9081
  client-ids:
    rest-client: admin-cli
    token: generate_token_dev
  client-secret: t4zOUwnAzsfZKHsr3QiDMh5QLWyb7s50

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka